import { NextResponse, type NextRequest } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { getCurrentSalonId } from '@/lib/auth';
import { SupplierOrderCreateSchema } from '@/schemas/supplier';
import { getSupplierProvider } from '@/lib/suppliers/manager';
import type { OrderStatus } from '@/types/supplier';

// ─── GET /api/supplier-orders — list orders with filters ────────────────────

export async function GET(request: NextRequest) {
  let salonId: string;
  try {
    salonId = await getCurrentSalonId();
  } catch {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const supabase = await createClient();
  const { searchParams } = request.nextUrl;

  const status = searchParams.get('status') as OrderStatus | null;
  const supplierId = searchParams.get('supplier_id');
  const limit = Math.min(Number(searchParams.get('limit')) || 50, 200);
  const offset = Number(searchParams.get('offset')) || 0;

  let query = supabase
    .from('supplier_orders')
    .select(
      `
      *,
      supplier:suppliers(id, name),
      items:supplier_order_items(id)
      `,
      { count: 'exact' },
    )
    .eq('salon_id', salonId)
    .order('created_at', { ascending: false })
    .range(offset, offset + limit - 1);

  if (status) {
    query = query.eq('status', status);
  }
  if (supplierId) {
    query = query.eq('supplier_id', supplierId);
  }

  const { data: orders, error, count } = await query;

  if (error) {
    console.error('[SUPPLIER-ORDERS] List error:', error.message);
    return NextResponse.json(
      { error: 'Помилка завантаження замовлень' },
      { status: 500 },
    );
  }

  const result = (orders ?? []).map((order) => ({
    ...order,
    items_count: Array.isArray(order.items) ? order.items.length : 0,
    items: undefined,
  }));

  return NextResponse.json({ data: result, count });
}

// ─── POST /api/supplier-orders — create order ──────────────────────────────

export async function POST(request: NextRequest) {
  let salonId: string;
  try {
    salonId = await getCurrentSalonId();
  } catch {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: 'Невалідний JSON' },
      { status: 400 },
    );
  }

  const parsed = SupplierOrderCreateSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: 'Помилка валідації', details: parsed.error.flatten() },
      { status: 422 },
    );
  }

  const { supplier_id, status, notes, items } = parsed.data;
  const supabase = await createClient();

  // Fetch supplier for discount_percent
  const { data: supplier, error: supplierErr } = await supabase
    .from('suppliers')
    .select('id, name, type, discount_percent, api_config')
    .eq('id', supplier_id)
    .eq('salon_id', salonId)
    .single();

  if (supplierErr || !supplier) {
    return NextResponse.json(
      { error: 'Постачальника не знайдено' },
      { status: 404 },
    );
  }

  // Calculate totals
  const subtotal = items.reduce(
    (sum, item) => sum + item.quantity * item.price_per_unit,
    0,
  );
  const discountPercent = supplier.discount_percent ?? 0;
  const discountAmount = Math.round(subtotal * (discountPercent / 100) * 100) / 100;
  const total = subtotal - discountAmount;

  // Insert order (order_number is auto-generated by DB trigger)
  const { data: order, error: orderErr } = await supabase
    .from('supplier_orders')
    .insert({
      salon_id: salonId,
      supplier_id,
      status: status ?? 'draft',
      subtotal,
      discount_amount: discountAmount,
      delivery_cost: 0,
      total,
      notes: notes ?? null,
      ordered_at: status !== 'draft' ? new Date().toISOString() : null,
    })
    .select('*')
    .single();

  if (orderErr || !order) {
    console.error('[SUPPLIER-ORDERS] Insert error:', orderErr?.message);
    return NextResponse.json(
      { error: 'Помилка створення замовлення' },
      { status: 500 },
    );
  }

  // Insert order items
  const orderItems = items.map((item) => ({
    order_id: order.id,
    supplier_product_id: item.supplier_product_id,
    inventory_item_id: item.inventory_item_id ?? null,
    quantity: item.quantity,
    price_per_unit: item.price_per_unit,
    total: item.quantity * item.price_per_unit,
    quantity_received: 0,
  }));

  const { data: insertedItems, error: itemsErr } = await supabase
    .from('supplier_order_items')
    .insert(orderItems)
    .select('*');

  if (itemsErr) {
    console.error('[SUPPLIER-ORDERS] Items insert error:', itemsErr.message);
    // Rollback: delete the order
    await supabase.from('supplier_orders').delete().eq('id', order.id);
    return NextResponse.json(
      { error: 'Помилка додавання товарів до замовлення' },
      { status: 500 },
    );
  }

  // If status !== 'draft', try to send order to supplier via provider
  let externalOrderId: string | null = null;
  if (status && status !== 'draft') {
    try {
      const provider = await getSupplierProvider(supabase, supplier_id);
      const result = await provider.createOrder({
        items: items.map((i) => ({
          productId: i.supplier_product_id,
          quantity: i.quantity,
        })),
        notes: notes ?? undefined,
      });
      externalOrderId = result.externalOrderId;

      await supabase
        .from('supplier_orders')
        .update({ external_order_id: externalOrderId })
        .eq('id', order.id);
    } catch (err) {
      console.warn(
        '[SUPPLIER-ORDERS] Provider createOrder failed (order saved as local):',
        err instanceof Error ? err.message : err,
      );
    }
  }

  return NextResponse.json(
    {
      data: {
        ...order,
        external_order_id: externalOrderId ?? order.external_order_id,
        items: insertedItems,
      },
    },
    { status: 201 },
  );
}
